name = "Rematch2"
uuid = "351a7294-9038-49b6-b9cf-e076b05af63f"
authors = ["RelationalAI"]
version = "0.2.7"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
MacroTools = "0.4, 0.5"
julia = "1.5"
