name = "Rematch2"
uuid = "351a7294-9038-49b6-b9cf-e076b05af63f"
authors = ["RelationalAI"]
version = "0.1.1"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.3"
MacroTools = "0.4, 0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
